// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiReservas.Data.Context;

#nullable disable

namespace MultiReservas.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    partial class SQLiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("MultiReservas.Models.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeLocais")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantidadeLocais")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReservasPorLocal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuantidadeLocais = 50
                        });
                });

            modelBuilder.Entity("MultiReservas.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("MultiReservas.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Local")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("MultiReservas.Models.ReservaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReservaId");

                    b.ToTable("ReservaItens");
                });

            modelBuilder.Entity("MultiReservas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdicionarItensReserva")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AdicionarReservas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CancelarReservas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Configuracao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EditarReservas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FinalizarReservas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Itens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PaginaInicial")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RemoverItensReserva")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Reservas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Usuarios")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdicionarItensReserva = true,
                            AdicionarReservas = true,
                            Ativo = true,
                            CancelarReservas = true,
                            Configuracao = true,
                            EditarReservas = true,
                            FinalizarReservas = true,
                            Itens = true,
                            Login = "admin",
                            PaginaInicial = true,
                            RemoverItensReserva = true,
                            Reservas = true,
                            Senha = "7a8b097ac97ab751667457209d1f714d7473283c000dee9e3cd2c59fa6977b40",
                            Usuarios = true
                        });
                });

            modelBuilder.Entity("MultiReservas.Models.Reserva", b =>
                {
                    b.HasOne("MultiReservas.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MultiReservas.Models.ReservaItem", b =>
                {
                    b.HasOne("MultiReservas.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MultiReservas.Models.Reserva", "Reserva")
                        .WithMany("ReservaItens")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("MultiReservas.Models.Reserva", b =>
                {
                    b.Navigation("ReservaItens");
                });
#pragma warning restore 612, 618
        }
    }
}
