CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Configuracoes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomeLocais" character varying(100),
    "QuantidadeLocais" integer NOT NULL,
    "ReservasPorLocal" integer,
    CONSTRAINT "PK_Configuracoes" PRIMARY KEY ("Id")
);

CREATE TABLE "Itens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" character varying(500) NOT NULL,
    "Preco" numeric(18,2) NOT NULL,
    "Ativo" boolean NOT NULL,
    CONSTRAINT "PK_Itens" PRIMARY KEY ("Id")
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Login" character varying(20) NOT NULL,
    "Senha" character varying(64) NOT NULL,
    "Ativo" boolean NOT NULL,
    "Reservas" boolean NOT NULL,
    "Itens" boolean NOT NULL,
    "Usuarios" boolean NOT NULL,
    "Configuracao" boolean NOT NULL,
    "PaginaInicial" boolean NOT NULL,
    "AdicionarReservas" boolean NOT NULL,
    "EditarReservas" boolean NOT NULL,
    "FinalizarReservas" boolean NOT NULL,
    "CancelarReservas" boolean NOT NULL,
    "AdicionarItensReserva" boolean NOT NULL,
    "RemoverItensReserva" boolean NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

CREATE TABLE "Reservas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer NOT NULL,
    "Local" integer NOT NULL,
    "Nome" character varying(100) NOT NULL,
    "Status" integer NOT NULL,
    "DataInicio" timestamp without time zone NOT NULL,
    "DataFim" timestamp without time zone,
    "Observacao" character varying(2000),
    CONSTRAINT "PK_Reservas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reservas_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReservaItens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReservaId" integer NOT NULL,
    "ItemId" integer NOT NULL,
    "Quantidade" integer NOT NULL,
    CONSTRAINT "PK_ReservaItens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReservaItens_Itens_ItemId" FOREIGN KEY ("ItemId") REFERENCES "Itens" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReservaItens_Reservas_ReservaId" FOREIGN KEY ("ReservaId") REFERENCES "Reservas" ("Id") ON DELETE CASCADE
);

INSERT INTO "Configuracoes" ("Id", "NomeLocais", "QuantidadeLocais", "ReservasPorLocal")
VALUES (1, NULL, 50, NULL);

INSERT INTO "Usuarios" ("Id", "AdicionarItensReserva", "AdicionarReservas", "Ativo", "CancelarReservas", "Configuracao", "EditarReservas", "FinalizarReservas", "Itens", "Login", "PaginaInicial", "RemoverItensReserva", "Reservas", "Senha", "Usuarios")
VALUES (1, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, 'admin', TRUE, TRUE, TRUE, '7a8b097ac97ab751667457209d1f714d7473283c000dee9e3cd2c59fa6977b40', TRUE);

CREATE INDEX "IX_ReservaItens_ItemId" ON "ReservaItens" ("ItemId");

CREATE INDEX "IX_ReservaItens_ReservaId" ON "ReservaItens" ("ReservaId");

CREATE INDEX "IX_Reservas_UsuarioId" ON "Reservas" ("UsuarioId");

SELECT setval(
    pg_get_serial_sequence('"Configuracoes"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Configuracoes") + 1,
        nextval(pg_get_serial_sequence('"Configuracoes"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Usuarios"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Usuarios") + 1,
        nextval(pg_get_serial_sequence('"Usuarios"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240717143105_Inicial', '8.0.7');

COMMIT;

